### PR TITLE
Design improvements

### PR DESCRIPTION
**Pull request by charypar**
Apply suggestions from #4.

better-colours

# to do

- [x] better colours
- [x] fix spacing

### CODE REVIEW

**Comment by charypar** [comment]
How is this spacing @clmntnbrn?

spacing

**Comment by clmntnbrn** [comment]
👍

**Comment by clmntnbrn** [comment]
How do you feel about the contrast between the bg colour of the rows? As in, there barely is any...

**Comment by clmntnbrn** [comment]
Also the outer indicator line (white one) starts way above the table, is this intentional? The app_api doesn't have a dot on it's line, and I'm not sure if it should or not - the behaviour of a line running by a row label with no dot doesn't happen anywhere else. But I may not understand because I don't understand what the dashboard is telling me 😉

**Comment by charypar** [comment]
I'm not sure about the contrast either - wanted to make the rows (services) a little easier to distinguish, but I'm not sure it's really working... any ideas?

The T-cap is intentionally above the table (maybe not high enough?), because it signifies that network is the one that takes connections from the outside.

The dots mean a connection to the network. The services just happen to be ordered in a way that the situation of network going past with no connection doesn't happen anywhere but the white one, with larger stacks and more complex networking setup, that would happen more often.

I was thinking about also drawing a horizontal line from the service name to the dot, to make it more obvious. Not yet sure whether I want to draw a single line through all of the connection, or move the dots vertically a little and draw parallel lines for each dot...

**Comment by clmntnbrn** [comment]
Hmm it's a tricky one. I've played with the colours in the swarm.html you gave me and there are these two solutions:

contrast

changing the contrast of the rows (maybe not this colour though, I haven't worked it out yet)

OR

white_lines

adding keylines (not going full width, I just couldn't be bothered to fix that 😉 )

**Comment by clmntnbrn** [comment]
Putting aside the colours etc, how do you feel about this spacing:

spacing

I just changed the margin on the `td li` to be `margin: 12px 6px;`

**Comment by charypar** [comment]
Ok, I made the spacing a little more airy, I think I'm happy with it now. Going to merge this. We should probably open an issue for a longer term discussion about design changes, I feel like the look may be evolving for a while :)

**Pull request merged**
