### PR TITLE
Security features: HTTPS, AUTHENTICATION, and redact docker event data before sending to the client

### PR DESCRIPTION
**Pull request by mohsenasm**
In this PR, I have added some security measures:

+ Now, we don't send **the whole docker event data**. The [main repo](https://github.com/charypar/swarm-dashboard) sends everything, including environment variables (someone might have stored some passwords in them, by mistake!).

+ Using the `ENABLE_AUTHENTICATION` environment variable, there is an option to use `Basic Auth`. The WebSocket server will close the connection if it does not receive a valid authentication token.

+ Using the `ENABLE_HTTPS` environment variable, there is an option to use `HTTPS` and `WSS`. We have Let’s Encrypt integration with the DNS challenge.

I have also added another feature. Now I change the background of service rows when they have no task (in case of a bad placement constraint, for example).

Note that you can use these new features on Docker image `mohsenasm/swarm-dashboard:v1.0`.

### CODE REVIEW

**Comment by charypar** [comment]
Hi @mohsenasm! Thanks for all the contributions, the code all looks good to me. Happy to merge these changes.

However, I have a proposition: Full disclosure - I no longer use docker swarm, and don't really have very much use for swarm-dashboard, or interest in maintaining it any more. I wonder whether, given the amount of work you've just done on it, , you'd be up for taking it over?

**Comment by mohsenasm** [comment]
Hi @charypar
That's okay since I am still using docker swarm and swarm-dashboard. However, because of using version 0.18.0 of Elm, the maintenance/development can be a bit slow.

**Comment by charypar** [comment]
I'm not sure I was quite clear enough in my previous message - I was suggesting I transfer the ownership of the repository to you (or your organisation).

Is that something you'd be interested in?

**Comment by mohsenasm** [comment]
Thanks. Yes, I'm interested in taking over the project. I think it's a valuable project for Docker Swarm users, and it's important to keep it growing with community support.

**Comment by charypar** [comment]
Ok, excellent, let me transfer the ownership 👍🏻

**Comment by charypar** [comment]
A-ha, slight trouble is that you already have a fork 🤔 when I try to transfer I get "mohsenasm/swarm-dashboard" already exists.

Let me start by at least inviting you as collaborator.

**Comment by mohsenasm** [comment]
We can merge the changes, and then delete the fork.

**Comment by mohsenasm** [comment]
I merged the changes.
I had added an automatic `docker push workflow` in my fork. It's failing now at the `docker login` phase.
To fix that, we should add the docker login's password in this section: `Settings > Secrets and variables > Actions > Environment secrets`
(I don't have access to this section)

**Comment by charypar** [comment]
I've requested the transfer, you should then have full control

**Pull request merged**
